# Site settings
title: Patricia Sylvester 
description: Portfolio 
keywords: Modern, Blogging, Fun
author: mgaringoDev
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
